### ISSUE TITLE
QuickLook works, but no icons on issues

### ISSUE THREAD

**Issue by Jakanapes** [MaddTheSane/Simple-Comic#17]
Downloaded from app store.  The QuickLook works and it shows the cover in the Preview pane of GetInfo, but the icons for the files are blue rectangles with the zipper on them, like I'd see for zip files, but only in the list or columns view in finder
![Screen Shot 2020-03-18 at 3 47 38 PM](https://user-images.githubusercontent.com/239207/77006053-cd7b2300-692f-11ea-9e11-65dab66b1a8e.jpg)

Icons show up in the icons and gallery views

**Comment by nickv2002** [comment]
Thanks for your feature request. This is a design decision to not show QuickLook thumbnails if your icon size is small enough they won't be very usable (for a small performance gain in large lists or over slow network connections). If you change your list view to have larger icons (Finder ➡️ View ➡️ Show View Options) you can see icons in the List View, and, as you noticed, the default icon size in other views is sufficiently large so that they will be shown.
