### ISSUE TITLE
Comics Sometimes Open in Small Windows

### ISSUE THREAD

**Issue by nickv2002** [MaddTheSane/Simple-Comic#6]
With the Simple Comic 2020-01-12 12-05-43 build I notarized ([Download here](https://towatchlist.com/files/Simple%20Comic%202020-01-12%2012-05-43.zip)), comics sometimes open in very small windows. Not sure what's causing it yet but I both @waha and I [experienced it](https://github.com/MaddTheSane/Simple-Comic/pull/4#issuecomment-575106677). Not a big deal but something worth looking in to…

**Comment by sygao** [comment]
I went looking for the source of this bug, but I've yet to get to the bottom of it. From what I can see, the second session in every batch of opened new sessions loads up with [isZoomed](https://developer.apple.com/documentation/appkit/nswindow/1419398-iszoomed) set to YES rather than NO. [TSSTSessionWindowController restoreSession](https://github.com/MaddTheSane/Simple-Comic/blob/0464d3b6bf31a35b9d93464e935459b1290b314b/Classes/Session/TSSTSessionWindowController.m#L927) calls a [zoom](https://developer.apple.com/documentation/appkit/nswindow/1419513-zoom) toggle on any new session ([right here](https://github.com/MaddTheSane/Simple-Comic/blob/0464d3b6bf31a35b9d93464e935459b1290b314b/Classes/Session/TSSTSessionWindowController.m#L963)), but given that it's a toggle, if isZoomed=YES, the zoom function shrinks the window back to its default size (460 x 529).

I've currently got a [cosmetic fix](https://github.com/sygao/Simple-Comic/commit/3aa998a5a34e6d69df48344b0b8044b521717b38) in place that prevents the window from calling the zoom toggle if the window is already zoomed. Is that too sloppy a fix?

**Comment by nickv2002** [comment]
Thanks for your help @sygao 
I’ll let @MaddTheSane weigh in on if this, but I’m happy to put up another build on the App Store with fixes (and Universal Binary Support!) whenever they’re ready.

**Comment by MaddTheSane** [comment]
Looks good. I'd like to fix the underlying issue, but this should be a good work-around for now.
