### ISSUE TITLE
QuickComic crashes when looking at WebP files

### ISSUE THREAD

**Issue by CyberSkull** [MaddTheSane/Simple-Comic#68]
QuickComic crashes when looking at a .cbz with WebP files in it.

macOS 10.15.7
SimpleComic 1.9.2 (274)

[crash.txt](https://github.com/MaddTheSane/Simple-Comic/files/8079854/crash.txt)

**Comment by CyberSkull** [comment]
The crash does not seem to be an issue in macOS 14.

**Comment by nickv2002** [comment]
I'm glad to hear this is working.

I can't really commit to supporting older versions of macOS simply due to lack of time and computing resources to run old versions. 

At this time the current version of macOS is 14.4.1 so if it works there I'm going to close this issue. Feel free to reopen if needed. Thanks!
