### ISSUE TITLE
Feature Request: Spotlight Metadata

### ISSUE THREAD

**Issue by SquaTront** [MaddTheSane/Simple-Comic#87]
It's nice that Simple Comic supports Quicklook in the Finder, so how about adding Spotlight searching of metadata? Here's a mdimporter on GitHub:

https://github.com/mike-ferenduros/ComicTagImporter

I believe that no app on the Mac is supporting searching of metadata via Spotlight atm.

**Comment by DavidPhillipOster** [comment]
Thanks! I was not aware of any standard for .cbz metadata - I thought a .cbz was just a .zip of image files. (Therefore, none of the .cbz I have have any metadata.) I'm most of the way through writing a Spotlight plugin for full-text indexing of .cbz so I'll definitely check out that [ComicTagImporter](https://github.com/mike-ferenduros/ComicTagImporter).

Probably packaged as a separate, free, download as a Release on my github repository page.

For me, I store my graphic novels in [Calibre](https://calibre-ebook.com), which does do metadata of any media you give it, and does, so far as I know, directly provide the metadata to Spotlight.

**Comment by DavidPhillipOster** [comment]
I recommend that we reject this feature request. [ComicTagImporter](https://github.com/mike-ferenduros/ComicTagImporter) looks for either a ComicInfo.xml file in the Graphic Novel, or it uses unzGetGlobalInfo64() to fetch a comment object from a .cbz (i.e., part of the Zip file format API) to extract JSON that it scans to contain metadata.

Since Simple Comic completely ignores both ComicInfo.xml  and the JSON in the .zip global comment, it isn't appropriate for Simple Comic to add a Spotlight Importer for that data.

This would be a good feature request for [Calibre](https://calibre-ebook.com/) though, since it allows users to edit, reads, provides spotlight importing, and writes metadata of many other file formats already.

**Comment by nickv2002** [comment]
Rejecting for the reasons @DavidPhillipOster outlined above. IE this is a better feature for Calibre or a stand-alone Spotlight plugin.
